### ISSUE TITLE
New Bug in fetch_data method.

### ISSUE THREAD

**Issue by frogman141** [martineastwood/penaltyblog#1]
I was unable to download data from football-data.co.uk and got the following error:

---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
Input In [97], in <cell line: 1>()
----> 1 df_pb = pb.footballdata.fetch_data("england", 2018, 0)

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/penaltyblog/footballdata/footballdata.py:64, in fetch_data(country, season_start_year, division)
     58 base_url = "[http://www.football-data.co.uk/mmz4281/{season}/{country}{division}.csv](http://www.football-data.co.uk/mmz4281/%7Bseason%7D/%7Bcountry%7D%7Bdivision%7D.csv)"
     60 url = base_url.format(
     61     season=season_str, country=country_code, division=str(division)
     62 )
---> 64 df = pd.read_csv(url)
     65 df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
     67 return df

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/util/_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/io/parsers/readers.py:680, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    665 kwds_defaults = _refine_defaults_read(
    666     dialect,
    667     delimiter,
   (...)
    676     defaults={"delimiter": ","},
    677 )
    678 kwds.update(kwds_defaults)
--> 680 return _read(filepath_or_buffer, kwds)

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/io/parsers/readers.py:581, in _read(filepath_or_buffer, kwds)
    578     return parser
    580 with parser:
--> 581     return parser.read(nrows)

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1250, in TextFileReader.read(self, nrows)
   1248 nrows = validate_integer("nrows", nrows)
   1249 try:
-> 1250     index, columns, col_dict = self._engine.read(nrows)
   1251 except Exception:
   1252     self.close()

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:225, in CParserWrapper.read(self, nrows)
    223 try:
    224     if self.low_memory:
--> 225         chunks = self._reader.read_low_memory(nrows)
    226         # destructive to chunks
    227         data = _concatenate_chunks(chunks)

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:805, in pandas._libs.parsers.TextReader.read_low_memory()

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:861, in pandas._libs.parsers.TextReader._read_rows()

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:847, in pandas._libs.parsers.TextReader._tokenize_rows()

File ~/miniconda3/envs/baseball/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:1960, in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 6

**Comment by martineastwood** [comment]
Thanks for the bug report, it looks like football-data.co.uk had altered the url the data was stored at. This should be fixed now.
