### ISSUE TITLE
Scrapers: inconsistance in competition mapping in common.py

### ISSUE THREAD

**Issue by Pincopiotta** [martineastwood/penaltyblog#10]
The competition mapping for "BEL First Division A" and "BEL First Division B"  are mapped to Germany.
In football-data there isn't a league file for the second division but only for Jupiler
below the code block:
COMPETITION_MAPPINGS = {
    "BEL First Division A": {
        "fbref": {
            "slug": "37",
            "stats": [
                "standard",
                "goalkeeping",
                "shooting",
                "playing_time",
                "misc",
            ],
        },
        "footballdata": {"slug": "**D2**"},
        "espn": {"slug": "**ger.2"},**
    },
    "**BEL First Division B**": {
        "fbref": {
            "slug": "69",
            "stats": [
                "standard",
                "goalkeeping",
                "playing_time",
                "misc",
            ],
        },
        "footballdata": {"slug": "D2"},
        "espn": {"slug": "ger.2"},

should be sufficient correct "footballdata": {"slug": "**D2**"}, to  "footballdata": {"slug": "**B1**"},
and remove the  part regarding  "BEL First Division B"

thank you for your very usefull project
Regards
Ale

**Comment by martineastwood** [comment]
Thanks for bug report, I’ll get that fixed and included in the next release

**Comment by martineastwood** [comment]
Should be fixed now in v0.8.0
