### ISSUE TITLE
Fbref Scraper - ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by aftershock9** [martineastwood/penaltyblog#11]
Encountering the following error when scraping FBREF with the following code.

fbref = pb.scrapers.FBRef("NLD Eredivisie", "2023-2024")
standard_stat = fbref.get_stats("standard")

Error message:

> > ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[3], line 1
> ----> 1 standard_stat = fbref.get_stats("standard")
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\penaltyblog\scrapers\fbref.py:266, in FBRef.get_stats(self, stat_type)
>     235 output["squad_for"] = (
>     236     dfs[0]
>     237     .pipe(self._flatten_stats_col_names)
>    (...)
>     243     .sort_index()
>     244 )
>     246 output["squad_against"] = (
>     247     dfs[1]
>     248     .pipe(self._flatten_stats_col_names)
>    (...)
>     254     .sort_index()
>     255 )
>     257 output["players"] = (
>     258     dfs[2]
>     259     .pipe(self._flatten_stats_col_names)
>     260     .pipe(sanitize_columns)
>     261     .query("rk != 'Rk'")
>     262     .drop(["rk", "matches"], axis=1)
>     263     .assign(season=self.season)
>     264     .assign(competition=self.competition)
>     265     .pipe(self._set_stat_col_types)
> --> 266     .pipe(self._player_ages)
>     267     .set_index("player")
>     268     .sort_index()
>     269 )
>     271 return output
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py:5839, in NDFrame.pipe(self, func, *args, **kwargs)
>    5781 @final
>    5782 @doc(klass=_shared_doc_kwargs["klass"])
>    5783 def pipe(
>    (...)
>    5787     **kwargs,
>    5788 ) -> T:
>    5789     r"""
>    5790     Apply chainable functions that expect Series or DataFrames.
>    5791 
>    (...)
>    5837     ...  )  # doctest: +SKIP
>    5838     """
> -> 5839     return com.pipe(self, func, *args, **kwargs)
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\common.py:513, in pipe(obj, func, *args, **kwargs)
>     511     return func(*args, **kwargs)
>     512 else:
> --> 513     return func(obj, *args, **kwargs)
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\penaltyblog\scrapers\fbref.py:131, in FBRef._player_ages(self, df)
>     127 """
>     128 Internal function to format the player ages
>     129 """
>     130 if "born" in df.columns:
> --> 131     df["born"] = df["born"].astype("int64")
>     133 if "age" in df.columns:
>     134     try:
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py:6240, in NDFrame.astype(self, dtype, copy, errors)
>    6233     results = [
>    6234         self.iloc[:, i].astype(dtype, copy=copy)
>    6235         for i in range(len(self.columns))
>    6236     ]
>    6238 else:
>    6239     # else, only a single dtype is given
> -> 6240     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
>    6241     return self._constructor(new_data).__finalize__(self, method="astype")
>    6243 # GH 33113: handle empty frame or series
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\managers.py:448, in BaseBlockManager.astype(self, dtype, copy, errors)
>     447 def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
> --> 448     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\managers.py:352, in BaseBlockManager.apply(self, f, align_keys, ignore_failures, **kwargs)
>     350         applied = b.apply(f, **kwargs)
>     351     else:
> --> 352         applied = getattr(b, f)(**kwargs)
>     353 except (TypeError, NotImplementedError):
>     354     if not ignore_failures:
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:526, in Block.astype(self, dtype, copy, errors)
>     508 """
>     509 Coerce to the new dtype.
>     510 
>    (...)
>     522 Block
>     523 """
>     524 values = self.values
> --> 526 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
>     528 new_values = maybe_coerce_values(new_values)
>     529 newb = self.make_block(new_values)
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:299, in astype_array_safe(values, dtype, copy, errors)
>     296     return values.copy()
>     298 try:
> --> 299     new_values = astype_array(values, dtype, copy=copy)
>     300 except (ValueError, TypeError):
>     301     # e.g. astype_nansafe can fail on object-dtype of strings
>     302     #  trying to convert to float
>     303     if errors == "ignore":
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:230, in astype_array(values, dtype, copy)
>     227     values = values.astype(dtype, copy=copy)
>     229 else:
> --> 230     values = astype_nansafe(values, dtype, copy=copy)
>     232 # in pandas we don't store numpy str dtypes, so convert to object
>     233 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:170, in astype_nansafe(arr, dtype, copy, skipna)
>     166     raise ValueError(msg)
>     168 if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype):
>     169     # Explicit copy, or required since NumPy can't view from / to object.
> --> 170     return arr.astype(dtype, copy=True)
>     172 return arr.astype(dtype, copy=copy)
> 
> ValueError: cannot convert float NaN to integer

**Comment by martineastwood** [comment]
That should be fixed now in 0.8.1 - I've changed the dtype of the offending column so it is nullable.
