### ISSUE TITLE
Time decay problem using local data

### ISSUE THREAD

**Issue by arthurfleck-jpg** [martineastwood/penaltyblog#12]
Hi,

I have noticed that there is issue in use the time-decay code when training with Dixon Coles model in local data

### Train with local data

I was using the quote like this:

`import sys`

sys.path.append("../../")

```
import pandas as pd

import penaltyblog as pb

df = pd.read_csv("/Users/user name/Desktop/E0.csv")
print(df)
weight = pb.models.dixon_coles_weights(df["date"], 0.001)
```

whenever i run this script i get this:

`TypeError: unsupported operand type(s) for /: 'str' and 'str'`

___________________________________________________________
### Train with scrapping data

```
df = pd.concat(
    [
        pb.scrapers.FootballData("ENG Premier League", "2019-2020").get_fixtures(),
        pb.scrapers.FootballData("ENG Premier League", "2020-2021").get_fixtures(),
        pb.scrapers.FootballData("ENG Premier League", "2021-2022").get_fixtures(),
    ]
)
weight = pb.models.dixon_coles_weights(df["date"], 0.001)
```

and the code is running smoothly.

I was trying add a line of int script to convert the str to int but it does not work,  I could not figure it out, could you maybe take a look? I'll be much appreciated !

Thanks,
Arthur

**Comment by martineastwood** [comment]
Hello Arthur - I suspect that when you've saved the data and then reloaded it into pandas one of the column dtypes has ended up as string.

The most likely is the date column so after loading the csv you can try doing something like:

df["date"] = pd.to_datetime(df["date"])
