### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by hedonistrh** [martineastwood/penaltyblog#2]
Hey, first of all thanks a lot for great blogposts and great package. I just would like to mention that there is a typo in the readme.

Following one 
```python
import penaltyblog as pb
pd.footballdata.list_countries()
```
should be
```python
import penaltyblog as pb
pb.footballdata.list_countries()
```

**Comment by martineastwood** [comment]
Thank you for letting me know, I've fixed this now
