### ISSUE TITLE
Data Fetch Issue with Some Leagues

### ISSUE THREAD

**Issue by hedonistrh** [martineastwood/penaltyblog#3]
Hey, I realized that some of leagues' data can not be fetched correctly. 

Following one is working
```python
df = pb.footballdata.fetch_data("england", 2021, 0)
```
Following ones are not working
```python
df = pb.footballdata.fetch_data("turkey", 2021, 0)
df = pb.footballdata.fetch_data("italy", 2021, 0)
```

Reduced issue as following
```bash
/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    639 class HTTPDefaultErrorHandler(BaseHandler):
    640     def http_error_default(self, req, fp, code, msg, hdrs):
--> 641         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    642
    643 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 300: Multiple Choices
```

**Comment by hedonistrh** [comment]
Following one is url from turkey related call though
```
https://www.football-data.co.uk/mmz4281/2122/T0.csv
```

When we go to that website, we see following...
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/34948815/178592438-e4c7b82c-e173-4e17-8c6d-61c36b0d7c4e.png">

**Comment by martineastwood** [comment]
Thanks for letting me know.

It looks like there are inconsistencies in how football-data are naming their files, I'll need to add something in to the code to handle this
