### ISSUE TITLE
Both teams to score probability

### ISSUE THREAD

**Issue by Chigstardan** [martineastwood/penaltyblog#4]
Very nice package, could you add both teams to score?

**Comment by martineastwood** [comment]
Good idea, I'm going to leave this issue open as a reminder to add it into the next update

**Comment by Chigstardan** [comment]
can you give me an idea on how to implement? Read your code, couldn't understand the _sum() function.

**Comment by martineastwood** [comment]
Off the top of my head, it's probably something like `self._sum(lambda a, b: a > 0  and b > 0)`

**Comment by Chigstardan** [comment]
I read your blog, and in one of the articles you used np.diag() to calculate draws for the matches , np.triagli() for home win. Using a similar approach, how do I select all score probabilities that both teams scored in to to calculate both teams to score and under and over?

**Comment by martineastwood** [comment]
The models already have a function for calculating over/under for total goals - `my_model.total_goals("under", 2.5)`

Both teams to score will be added in an update early next week

**Comment by martineastwood** [comment]
I'm closing this issue now as the probability of both teams to score has been released in v0.4.0, which is now on pypi
