### ISSUE TITLE
KeyError: 'Time' for Football Data pre 2018

### ISSUE THREAD

**Issue by wormwood** [martineastwood/penaltyblog#5]
Hi

Running the code below raises a KeyError: 'Time' error

    fbd = pb.scrapers.FootballData("ENG Premier League", "2018-2019")
    df = fbd.get_fixtures()
    
    df.head()

I know footballdata.co.uk added the match time to the CSV's in the following season- I assume this is the problem, but am I missing something?

Many thanks - great resource!
Richard

**Comment by martineastwood** [comment]
Thanks Richard, yes you're correct about the problem. It will be fixed in the next release, which is probably about a week away. Thanks for the bug report!
